services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  n8n-main:
    build: .
    restart: unless-stopped
    environment:
      N8N_QUEUE_TYPE: "redis"
      QUEUE_BULL_REDIS_HOST: "redis"

      NODE_ENV: "production"
      N8N_DISABLE_UI: "true"
      N8N_TEMPLATES_ENABLED: "false"
      N8N_COMMUNITY_NODES_DISABLED: "true"
      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_HIRING_BANNER_ENABLED: "false"
      N8N_PERSONALIZATION_ENABLED: "false"

      N8N_HOST: "n8n"
      N8N_PORT: 5678
      WEBHOOK_URL: "http://localhost:5678"
    ports:
      - "5678:5678"
    depends_on:
      - redis
    command: "n8n"

  n8n-worker:
    build: .
    restart: unless-stopped
    environment:
      N8N_QUEUE_TYPE: "redis"
      QUEUE_BULL_REDIS_HOST: "redis"

      NODE_ENV: "production"
      EXECUTIONS_PROCESS: "main"

      N8N_DISABLE_UI: "true"
      N8N_TEMPLATES_ENABLED: "false"
      N8N_COMMUNITY_NODES_DISABLED: "true"
      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_HIRING_BANNER_ENABLED: "false"
      N8N_PERSONALIZATION_ENABLED: "false"
    depends_on:
      - redis
    command: "n8n worker"
